graph [
	node [ id 0 label "0" ]
	node [ id 1 label "0" ]
	node [ id 2 label "0" ]
	node [ id 4 label "0" ]
	node [ id 5 label "0" ]
	node [ id 6 label "0" ]
	node [ id 8 label "0" ]
	edge [ source 0 target 1 label "-" ]
	edge [ source 0 target 2 label "-" ]
	edge [ source 4 target 5 label "-" ]
	edge [ source 4 target 6 label "-" ]
	edge [ source 0 target 8 label "-" ]
	edge [ source 8 target 4 label "-" ]
]
